export * from "./SubmitCheck";
export * from "./Submitted";
export * from "./application";
export * from "./score";
export * from "./ActivityGraduate";
export * from "./ActivityProspectiveGraduate";
export * from "./applicationCheck";
export * from "./Landing";
export * from "./Page404";
