export { default as search } from "./search.svg";
export { default as left } from "./left.svg";
export { default as right } from "./right.svg";
export { default as cancel } from "./cancel.svg";
export { ApplicationPeriodIcon } from "./01ApplicationPeriodIcon";
export { AdmissionRateIcon } from "./02AdmissionRateIcon";
export { CompetitionRateIcon } from "./03CompetitionRateIcon";
export { FirstRoundDeadlineIcon } from "./04FirstRoundDeadlineIcon";
export { OneIcon } from "./OneIcon";
export { TwoIcon } from "./TwoIcon";
export { ThreeIcon } from "./ThreeIcon";
export { FourIcon } from "./FourIcon";
export { ArrowIcon } from "./ArrowIcon";
