export * from "./Arrow";
export * from "./EntryLogo";
export * from "./Graph";
export * from "./School";
export * from "./Trophy";
export * from "./Check";
export * from "./Cancel";
export * from "./SideBarBtnIcon";
export * from "./ArrowNav";
export * from "./Photo";
export * from "./Caution";
export * from "./ImageChange";
export * from "./Search";
export * from "./OXIcons";
export { default as dropdownArrow } from "./dropdownArrow.svg";
export * from "./Eye";
export { default as modalCancel } from "./modalCancel.svg";
