export * from "./arrow";
export * from "./entryLogo";
export * from "./graph";
export * from "./school";
export * from "./trophy";
export * from "./check";
export * from "./cancel";
export * from "./sideBarBtnIcon";
export * from "./arrowNav";
export * from "./photo";
export * from "./caution";
export * from "./imageChange";
export * from "./search";
export * from "./oxIcons";
export { default as dropdownArrow } from "./dropdownArrow.svg";
export * from "./eye";
export { default as modalCancel } from "./modalCancel.svg";
